# Generated by Django 5.2.8 on 2025-11-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_student_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default='images/default_image.png', upload_to='course_images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_photo',
            field=models.ImageField(default='images/default_image.png', upload_to='student_photos/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trainer_photo',
            field=models.ImageField(default='images/default_image.png', upload_to='trainer_photos/'),
        ),
    ]
